name: Documentation Bug Report
description: File a bug report relating to the GameMaker Manual, a wiki page or a support FAQ
type: 'Docs Bug'
labels: ["documentation"]
projects: ["YoYoGames/17"]
body:
  - type: markdown
    attributes:
      value: |
        Search for existing reports for this bug first! If a report already exists, DO NOT send another report now - just leave a thumbs-up/comment on the other report instead.
       
        Most fields need to be filled-in before you can click Submit, as everything is required information for us to confirm and fix this bug.

  - type: textarea
    id: description
    attributes:
      label: What is the bug?
      description: Write a thorough description of the issue. You may paste screenshots at suitable locations in your text.
    validations:
      required: true
      
  - type: input
    id: link
    attributes:
      label: Manual Link
      description: Please add a link to the relevant manual page here
    validations:
      required: false
 
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
