name: Documentation Bug Report
description: File a bug report relating to the GameMaker Manual or a support FAQ
type: 'Docs Bug'
labels: ["documentation"]
projects: ["YoYoGames/17"]
body:
  - type: markdown
    attributes:
      value: |
        Search for existing reports of this bug first! If one exists, DO NOT send your own report, instead leave a thumbs-up/comment on the existing one.

        Most fields need to be filled-in before you can submit this report, as it's required information so we can confirm and fix this bug.

  - type: textarea
    id: description
    attributes:
      label: What is the bug?
      description: Write a thorough description of the issue. You may paste screenshots at suitable locations in your text.
    validations:
      required: true
      
  - type: input
    id: link
    attributes:
      label: Manual Link
      description: Please add a link to the relevant manual page here
    validations:
      required: false
 
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
