name: IDE Bug Report
description: File a bug report relating to general usage of the GameMaker IDE (no sign-in or "missing platforms in Target Manager" issues - for these, use the GameMaker Account Support option below!)
labels: ["ide-bug"]
body:
  - type: markdown
    attributes:
      value: |
        For any GameMaker Account sign-in or licencing issues (including "I can't see all my platforms in Target Manager") please submit a [Helpdesk Ticket](https://contact.gamemaker.io/contact-us#account) instead of using this form.
        
        Please also ensure you have searched for any existing reports of this issue before you begin - if one exists, please leave a thumbs-up and/or a comment on that one, rather than knowingly filing a duplicate report, as duplicates just slow things down.
       
        Note that most fields are required to be filled-in before you can submit this report, as it is all essential information which we will require in order to confirm and fix your issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Write a concise yet detailed description of the issue and do include any relevant screenshots at suitable locations in the body of your text. Please do not type/paste lots of code in this field - attach a sample project instead, as requested below. (Also, do not add a web link as your entire bug report and assume we will read the external thread to work it out ourselves, as we will most likely simply close the report!)
    validations:
      required: true
      
  - type: input
    id: expected
    attributes:
      label: Expected Change
      description: If it is not obvious from your Description text, what difference would you expect to see once this is fixed?
    validations:
      required: false
      
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Add detailed, ordered steps for someone else to recreate the issue into the gaps below (add as many steps into the middle as you require)
      value: |
        1. Start GameMaker
        2. 
        3. 
        4. See the issue
    validations:
      required: true
      
  - type: dropdown
    id: repro-rate
    attributes:
      label: How reliably can you recreate this issue using your steps above?
      options:
        - Always
        - Most Times
        - Only Sometimes
        - Rarely
        - Only Ever Happened Once 
    validations:
      required: true
      
  - type: dropdown
    id: version
    attributes:
      label: Which version of GameMaker are you reporting this issue for?
      description: If you are on an older version, update and confirm your issue stil exists! And if you are using a Beta, please add the full version number into your Description text.
      multiple: true
      options:
        - 2024.13.1 (Monthly)
        - 2022.0.3 (LTS)
        - 2024.1300 (Betas)
    validations:
      required: true
      
  - type: dropdown
    id: os
    attributes:
      label: Which operating system(s) are you seeing the problem on?
      multiple: true
      options: 
        - Windows 11
        - Windows 10
        - Windows 7/8
        - macOS Sequoia
        - macOS Sonoma
        - macOS Ventura
        - macOS Monterey
        - macOS Big Sur
        - Ubuntu 24 LTS
        - Ubuntu 22 LTS
        - Ubuntu 20 LTS
        - ChromeOS
    validations:
      required: false
      
  - type: dropdown
    id: steam
    attributes:
      label: Are you running GameMaker from inside your Steam library?
      options:
        - "Yes"
        - "No"
    validations:
      required: false
      
  - type: checkboxes
    id: zip-file
    attributes:
      label: Sample Package Attached?
      description: This .zip file is essential for all bug reports. Please build your project, so that you have a compiler log showing inside GameMaker, then open the Help menu inside GameMaker and run the "Upload a Bug/Ticket Sample" tool. Paste the download link GameMaker makes for you into the Description of your report.
      options:
        - label: I have attached my bug package
          required: true
      
  - type: checkboxes
    id: sample
    attributes:
      label: Sample Project Added?
      description: When you created your Bug Package did you say yes to including your project, or have you manually attached a project .yyz directly onto this report? (Note that we will ask for a sample if the issue does not easily reproduce for us when following your steps.)
      options:
        - label: I have included a small sample project
          required: false
 
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
