name: GMS2 In-Game Bug Report
description: File a bug report for in-game issues found on a GMS2 target
type: 'In-Game Bug'
labels: ["gms2-bug"]
projects: ["YoYoGames/17"]
body:
  - type: markdown
    attributes:
      value: |
        Search for existing reports of this bug first! If one exists, DO NOT send your own report, instead leave a thumbs-up/comment on the existing one.
       
        Most fields need to be filled-in before you can submit this report, as it's required information so we can confirm and fix this bug.

  - type: textarea
    id: description
    attributes:
      label: What Is The Bug?
      description:  Write a thorough description of the issue. You may paste screenshots and links at suitable locations in your text. (However, DO NOT add a web link and assume we will read and guess at the bug ourselves - we will simply close the report.)
    validations:
      required: true
      
  - type: input
    id: expected
    attributes:
      label: Expected Change
      description: If it is not obvious from your Description text, what difference would you expect to see once this is fixed?
    validations:
      required: false
      
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Add detailed, ordered steps for someone else to recreate the issue (add as many steps into the gaps below as you require)
      value: |
        1. Start GameMaker
        2. 
        3. 
        4. See the issue
    validations:
      required: true
      
  - type: dropdown
    id: repro-rate
    attributes:
      label: How reliably can you recreate this issue using your steps above?
      options:
        - Always
        - Most Times
        - Only Sometimes
        - Rarely
        - Only Ever Happened Once 
    validations:
      required: true
      
  - type: dropdown
    id: version
    attributes:
      label: Which version of GameMaker are you reporting this issue for?
      description: If you are on an older version, update and confirm your issue stil exists! And if you are using a Beta, please add the full version number into your Description text.
      multiple: true
      options:
        - 2024.14.1 Monthly
        - 2022.0.3 LTS
        - 2024.1400.1 Betas
    validations:
      required: true
      
  - type: dropdown
    id: platforms
    attributes:
      label: Which platform(s) are you seeing the problem on?
      multiple: true
      options: 
        - Windows
        - macOS
        - Ubuntu
        - Android
        - GX.games
        - HTML5
        - iOS
        - PlayStation 4
        - PlayStation 5
        - Switch
        - Switch 2
        - tvOS
        - Xbox
    validations:
      required: true
      
  - type: input
    id: sample
    attributes:
      label: Sample Package
      description: A bug package file is essential for all In-Game reports. Please recreate the problem and then use the Help > Upload a Bug Sample tool inside GameMaker. If possible, say yes to including your sample project! Then paste the download URL into the box below.
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
