name: Prefab Bug Report
description: File a bug report for issues that happen with any of our official Prefab Collections (before they have been modified by you)
type: 'Prefab Bug'
labels: ["prefab"]
projects: ["YoYoGames/17"]
body:
  - type: markdown
    attributes:
      value: |
        Always ensure you are using the latest versions of all prefab collections in your project and that you have reviewed the documentation for each prefab to ensure they are all set up correctly, as no coding advice/support is offered here - if you want to ask a coding question, please ask [the GameMaker Community](https://forum.gamemaker.io/index.php?forums/tech-support.24/) instead of using this form.
        
        Search for existing reports for this bug first! If a report already exists, DO NOT send another report now - just leave a thumbs-up/comment on the other report instead.
       
        Most fields need to be filled-in before you can click Submit, as everything is required information for us to confirm and fix this bug.

  - type: input
    id: collectionname
    attributes:
      label: Which Prefab Collection are you reporting this issue for?
      description: Type/paste in the full name (including the version number) of the Prefab Collection 
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: What Is The Bug?
      description: Write a thorough description of the issue and ensure you make it clear which specific individual Prefab(s) within the colllection are at fault. You may paste screenshots and links at suitable locations in your text. (However, DO NOT add a web link and assume we will read an external discussion and guess at the bug ourselves - we will simply close the report.)
    validations:
      required: true
      
  - type: input
    id: expected
    attributes:
      label: Expected Change
      description: If it is not obvious from your Description text, what difference would you expect to see once this is fixed?
    validations:
      required: false
      
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Add detailed, ordered steps for someone else to recreate the issue (add as many steps into the gaps below as you require)
      value: |
        1. Start GameMaker and open my attached project
        2. 
        3. 
        4. See the issue
    validations:
      required: true
      
  - type: dropdown
    id: repro-rate
    attributes:
      label: How reliably can you recreate this issue using your steps above?
      options:
        - Always
        - Most Times
        - Only Sometimes
        - Rarely
        - Only Ever Happened Once 
    validations:
      required: true
      
  - type: dropdown
    id: version
    attributes:
      label: Which version(s) of GameMaker are you reporting this issue for?
      description: If you are on an older version than the Monthly shown below, install this Monthly version and confirm your issue still exists before you report anything! If you are using a Beta newer than the Monthly, please also add the full version number into your Description text above.
      multiple: true
      options:
        - 2024.14.3 Monthly
        - 2024.1400.3 Betas
    validations:
      required: true
      
  - type: dropdown
    id: platforms
    attributes:
      label: Which platform(s) are you seeing the problem on?
      multiple: true
      options: 
        - Windows
        - macOS
        - Ubuntu
        - Android
        - GX.games
        - HTML5
        - iOS
        - PlayStation 4
        - PlayStation 5
        - Switch
        - Switch 2
        - tvOS
        - Xbox
    validations:
      required: true
      
  - type: input
    id: sample
    attributes:
      label: Sample Package
      description: A bug package file is essential for all prefab reports, as we need to know if the problem is in our code or yours. Please recreate the problem and then use the Help > Upload a Bug Sample tool inside GameMaker. Say yes to including your sample project! Then paste the download URL into the box below.
    validations:
      required: true
          
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
