name: ProjectTool Bug Report
description: File a bug report for issues when ProjectTool says it failed importing/exporting .yyz projects, Marketplace/Local .yymps packages, Prefab Collections, or Start Page templates
type: 'Plugin Bug'
labels: ["plugin", "ProjectTool"]
projects: ["YoYoGames/17"]
body:
  - type: markdown
    attributes:
      value: |
        Always ensure you are using the latest versions of ProjectTool **and** any Prefab/Template/Package and that you have reviewed the documentation within each to ensure they are all set up correctly. Note that if you downloaded the Template via the Start Page this will not automatically update when new versions of the template are released - you need to download your copy of the template and then download the new one!
        
        Search for existing reports of this bug first! If one exists, DO NOT send your own report, instead leave a thumbs-up/comment on the existing one.

        Most fields need to be filled-in before you can submit this report, as it's required information so we can confirm and fix this bug.
        
        No coding advice/support is offered here - if you want to ask a coding question, please ask [the GameMaker Community](https://forum.gamemaker.io/index.php?forums/tech-support.24/) instead of using this form.
    
  - type: textarea
    id: description
    attributes:
      label: What Is The Bug?
      description: Write a thorough description of the issue and ensure you make it clear which specific individual YYZ/Asset/Package/Prefab/Template are at fault. You may paste screenshots and links at suitable locations in your text. (However, DO NOT add a web link and assume we will read the external page and guess at the bug ourselves - we will simply close the report.)
    validations:
      required: true
      
  - type: input
    id: expected
    attributes:
      label: Expected Change
      description: If it is not obvious from your Description text, what difference would you expect to see once this is fixed?
    validations:
      required: false
      
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Add detailed, ordered steps for someone else to recreate the issue (add as many steps into the gaps below as you require)
      value: |
        1. Start GameMaker
        2. 
        3. 
        4. See the issue
    validations:
      required: true
      
  - type: dropdown
    id: repro-rate
    attributes:
      label: How reliably can you recreate this issue using your steps above?
      options:
        - Always
        - Most Times
        - Only Sometimes
        - Rarely
        - Only Ever Happened Once 
    validations:
      required: true
      
  - type: dropdown
    id: version
    attributes:
      label: Which version of GameMaker are you reporting this issue for?
      description: If you are on an older version, update and confirm your issue stil exists! And if you are using a Beta, please add the full version number into your Description text.
      multiple: true
      options:
        - 2024.14.1 Monthly
        - 2022.0.3 LTS
        - 2024.1400.1 Betas
    validations:
      required: true
      
  - type: input
    id: sample
    attributes:
      label: Sample Package
      description: A bug package file is essential for all ProjectTool reports. Please recreate the problem and then zip up any failed project folder, then use the Help > Upload a Bug Sample tool inside GameMaker to send us that .zip AND all .yyz/.yymps/Prefab files that are required to recreate this issue. Then paste the download URL into the box below.
    validations:
      required: true
          
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
