name: Issue Comment → Project Triage 

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write
  pull-requests: write
  repository-projects: write    

jobs:
  issue-comment-triage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Generate App token to publish CI check
        uses: actions/create-github-app-token@v2
        id: generate-token
        with:
            app-id: ${{ secrets.AUTOMATON_APP_ID }}
            private-key: ${{ secrets.AUTOMATON_PRIVATE_KEY }}    
            owner: YoYoGames
            repositories: ${{ github.repository }}
      
      - name: Run the Script
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          python .github/workflows/actions/comment_issue.py
