name: Ask for project

on:
  issues:
    types:
      - labeled

permissions:
  contents: read
  issues: write

jobs:
  add-comment:
    if: github.event.label.name == 'project required'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Debug
        run: |
          echo "Triggered label: ${{ github.event.label.name }}"
          echo "Issue number: ${{ github.event.issue.number }}"

      - name: Check if comment already exists
        id: check_comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
        run: |
          EXISTING=$(gh issue view "$NUMBER" --json comments \
            --jq '.comments[].body' | grep -c "project-required-comment" || true)

          echo "exists=$EXISTING" >> $GITHUB_OUTPUT

      - name: Add comment
        if: steps.check_comment.outputs.exists == '0'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
        run: |
          gh issue comment "$NUMBER" --body "$(cat <<'EOF'
          <!-- project-required-comment -->

          Thanks for reporting this, but in order to confirm the problem and then investigate a fix we need you to send us small project which already shows this issue.

          Open the project inside GameMaker and use the Help menu's "Upload a Bug/Ticket Sample" tool.

          Thanks!
          EOF
          )"

      - name: Remove label
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
          LABEL: ${{ github.event.label.name }}
        run: |
          gh issue edit "$NUMBER" --remove-label "$LABEL"
